### ISSUE TITLE
MakeTable

### ISSUE THREAD

**Issue by sjbeckett** [sjbeckett/localcovid19now#47]
Suggested changes to MakeTable @ar0ch @freyja-bt 

1) `calc_risk` performs a rounding operation, not sure we need additional rounding in `create_c19r_data`:  https://github.com/sjbeckett/subregionalcovid19/blob/7f712fd46f21385dc7e55c540a761654a58f45af/R/MakeTable.R#L69 . Suggest we replace `calc_risk` with `estRisk` and remove `calc_risk` from package
2) I'm finding `create_c19r_data` attempts to export geometry to csv (but in doing so causes issues!). I'm not sure it needs to return geometry as we have a geoid. Can we drop the geometry column?

**Comment by freyja-bt** [comment]
question 2 is fixed in the most recent commit.

**Comment by ar0ch** [comment]
That'll be a pretty wide dataframe. Why not provide it in 'ABm (ABL-ABH)' format?
