### ISSUE TITLE
Outdated: Spain Data Source

### ISSUE THREAD

**Issue by rkassa** [sjbeckett/localcovid19now#54]
It looks like the [regional case data csv](https://cnecovid.isciii.es/covid19/resources/casos_tecnica_provincia.csv) is no longer being updated for Spain. The last reported date is 2022-04-05.

It looks like their reported data is now limited to people over 60 years of age, or just hospitalizations and ICU admissions?

Their documentation & data is [here](https://cnecovid.isciii.es/covid19/#documentaci%C3%B3n-y-datos)

(cc: @kaitejohnson)

**Comment by kaitejohnson** [comment]
Hey yes! We discussed this a while ago, they are no longer reporting cases in those below 60. We should probably take them off the map.

**Comment by sjbeckett** [comment]
Yes, agree we should not change this to the new age-limited data set.
