### ISSUE TITLE
Plans on adding unit tests?

### ISSUE THREAD

**Issue by welch16** [sjbeckett/localcovid19now#62]
Hi @sjbeckett,

I was wondering if there are any plans to add unit tests with `testthat` or an alternative package. I know that other organizations like bioconductor or ropensci recommend adding unit tests.

I know the amount of work required to add tests to a package of the scope as this one, but I feel it would be enriched in the end.

Thanks

**Comment by sjbeckett** [comment]
Unit tests for some core functions added with #67
